FROM gcr.io/distroless/base-debian12:nonroot

WORKDIR /
COPY --chown=nonroot:nonroot server /server

ENV APP_ENV=production
ENV PORT=8080
ENV SQLITE_PATH=/data/backend.sqlite

EXPOSE 8080

ENTRYPOINT ["/server"]
